### ISSUE TITLE
CS CENTERS: SPARKING STUDENT INTEREST THROUGH CHOICE

### ISSUE THREAD

**Issue by cs4allnyc** [nycdoe-cs4all/blueprint-learning-site#69] opened 2017-07-28 15:35 UTC
http://blueprint.cs4all.nyc/resources/7/

None of the links to key terms work
![404 error](https://user-images.githubusercontent.com/17147758/28724650-bfdd7968-7388-11e7-993b-2ca883e14882.PNG)

**Comment by ritammehta** [comment] 2017-07-28 17:11
I can't reproduce this problem across browsers and operating systems. That link should lead to a modal popping up. Can you detail your setup?

**Comment by aankit** [comment] 2017-07-31 20:20
I'm closing this because it seems to be working. Maybe won't work in IE, but I'm not worried about that for now.

**Closed by aankit** 2017-07-31 20:20 UTC
